apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: nodejs-kubernetes
  name: nodejs-kubernetes
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nodejs-kubernetes
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/nodejs-mongodb-kubernetes-default: "true"
        io.kompose.service: nodejs-kubernetes
    spec:
      containers:
        - env:
            - name: ACCESS_TOKEN_SECRET_KEY
              value: 9ec569f2488d0303fe54aaeabcb0ffeefca54e7f466eb99b92db7e1df3eecca7
            - name: MONGO_DB_URL
              value: mongodb://nodejs-kubernetes-mongodb:27017/nodejs-kubernetes
            - name: NODE_ENV
              value: testssda
            - name: PASSWORD_HASH
              value: paymentC103V1TestEnv123***
            - name: PORT
              value: "80"
            - name: REFRESH_TOKEN_SECRET_KEY
              value: 9ec569f2488d0303fe54aaeabcb0ffeefca54e7f466eb99b92db7e1df3eecca7paymentC103V1TestEnv123***
          image: local-nodejs-kubernetes:1
          name: nodejs-kubernetes
          imagePullPolicy: Never
          ports:
            - containerPort: 80
              hostPort: 8099
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
